src/DW/UserBundle/Entity/User.php
<?php
/**
 * @author Yann-Eric <yann-eric@live.fr>
 */
namespace DW\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\JoinTable;

/**
 * DW\UserBundle\Entity\User
 *
 * @ORM\Table(name="dw_user")
 * @ORM\Entity(repositoryClass="DW\UserBundle\Entity\UserRepository")
 */
class User
{
    
    /** @ManyToMany(targetEntity="Role", cascade={"persist"}) 
     *  @JoinTable(name="dw_user_role")
     */
    private $roles;
    
     public function getRoles() {
        return $this->roles;
    }
    
     public function getStringRoles() {
        
        $string_roles = '';
         foreach ($this->roles as $key => $value) {
             $string_roles .= $value->getName().' / ';
             
         }
         return $string_roles; 
        
    }
    
    public function addRole($role) {
        $this->roles[] = $role;
    }
    
    public function removeRole($role) {
       // Not implemented here  
      
    }
    
    
    
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $username
     *
     * @ORM\Column(name="username", type="string", length=255)
     */
    private $username;

    /**
     * @var string $email
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=true, unique=true)
     */
    private $email;
    
    /**
     * @var string $password
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;
    
    /**
     * @var string $encrypted_password
     *
     * @ORM\Column(name="encrypted_password", type="string", length=255)
     */
    private $encrypted_password;

    /**
     * @var boolean $enabled
     *
     * @ORM\Column(name="enabled", type="boolean", nullable=true)
     */
    private $enabled;

    /**
     * @var boolean $accountExpired
     *
     * @ORM\Column(name="accountExpired", type="boolean", nullable=true)
     */
    private $accountExpired;

    /**
     * @var boolean $accountLocked
     *
     * @ORM\Column(name="accountLocked", type="boolean", nullable=true)
     */
    private $accountLocked;
  
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;
    
        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }
    
    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;
        $this->setEncryptedPassword($password);
    
        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }
    
    /**
     * Set encrypted_password
     *
     * @param string $encrypted_password
     * @return User
     */
    public function setEncryptedPassword($password)
    {
        $this->encrypted_password = sha1($password);
    
        return $this;
    }

    /**
     * Get encrypted_password
     *
     * @return string 
     */
    public function getEncryptedPassword()
    {
        return $this->encrypted_password;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return User
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;
    
        return $this;
    }

    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Set accountExpired
     *
     * @param boolean $accountExpired
     * @return User
     */
    public function setAccountExpired($accountExpired)
    {
        $this->accountExpired = $accountExpired;
    
        return $this;
    }

    /**
     * Get accountExpired
     *
     * @return boolean 
     */
    public function getAccountExpired()
    {
        return $this->accountExpired;
    }

    /**
     * Set accountLocked
     *
     * @param boolean $accountLocked
     * @return User
     */
    public function setAccountLocked($accountLocked)
    {
        $this->accountLocked = $accountLocked;
    
        return $this;
    }

    /**
     * Get accountLocked
     *
     * @return boolean 
     */
    public function getAccountLocked()
    {
        return $this->accountLocked;
    }
    



}

src/DW/UserBundle/Form/UserType.php
<?php
/**
 * @author Yann-Eric <yann-eric@live.fr>
 */
namespace DW\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('email')
            ->add('password')
//            ->add('encrypted_password')
            ->add('enabled')
            ->add('accountExpired')
            ->add('accountLocked')
            ->add('roles')
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'DW\UserBundle\Entity\User'
        ));
    }

    public function getName()
    {
        return 'dw_userbundle_usertype';
    }
}

src/DW/UserBundle/Controller/UserController.php
<?php
/**
 * @author Yann-Eric <yann-eric@live.fr>
 */
namespace DW\UserBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use DW\UserBundle\Entity\User;
use DW\UserBundle\Form\UserType;

/**
 * User controller.
 *
 */
class UserController extends Controller
{
    /**
     * Lists all User entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('DWUserBundle:User')->findAll();

        return $this->render('DWUserBundle:User:index.html.twig', array(
            'entities' => $entities,
        ));
    }

    /**
     * Finds and displays a User entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('DWUserBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('DWUserBundle:User:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),        ));
    }

    /**
     * Displays a form to create a new User entity.
     *
     */
    public function newAction()
    {
        $entity = new User();
        $form   = $this->createForm(new UserType(), $entity);

        return $this->render('DWUserBundle:User:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a new User entity.
     *
     */
    public function createAction(Request $request)
    {
        $entity  = new User();
        $form = $this->createForm(new UserType(), $entity);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('user_show', array('id' => $entity->getId())));
        }

        return $this->render('DWUserBundle:User:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing User entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('DWUserBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $editForm = $this->createForm(new UserType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('DWUserBundle:User:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Edits an existing User entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('DWUserBundle:User')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find User entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new UserType(), $entity);
        $editForm->bind($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('user_edit', array('id' => $id)));
        }

        return $this->render('DWUserBundle:User:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a User entity.
     *
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->bind($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('DWUserBundle:User')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find User entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('user'));
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
}

src/DW/UserBundle/Resources/views/User/edit.html.twig
<h1>User edit</h1>

<form action="{{ path('user_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
    {{ form_widget(edit_form) }}
    <p>
        <button type="submit">Edit</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('user') }}">
            Back to the list
        </a>
    </li>
    <li>
        <form action="{{ path('user_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>

src/DW/UserBundle/Resources/views/User/index.html.twig
<h1>User list</h1>

<table class="records_list" border="1">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Email</th>
            <th>Password</th>
           <!--<th>Encrypted_password</th>-->
            <th>Enabled</th>
            <th>Accountexpired</th>
            <th>Accountlocked</th>
            <th>Roles</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        <tr>
            <td><a href="{{ path('user_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
            <td>{{ entity.username }}</td>
            <td>{{ entity.email }}</td>
            <td>{{ entity.password }}</td>
            <!--<td>{{ entity.encryptedpassword }}</td>-->
            <td>{{ entity.enabled }}</td>
            <td>{{ entity.accountExpired }}</td>
            <td>{{ entity.accountLocked }}</td>
            <td>{{ entity.stringRoles }}</td>
            <td>
                <ul>
                    <li>
                        <a href="{{ path('user_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('user_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<ul>
    <li>
        <a href="{{ path('user_new') }}">
            Create a new entry
        </a>
    </li>
</ul>

src/DW/UserBundle/Resources/views/User/new.html.twig
<h1>User creation</h1>

<form action="{{ path('user_create') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <p>
        <button type="submit">Create</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('user') }}">
            Back to the list
        </a>
    </li>
</ul>

src/DW/UserBundle/Resources/views/User/show.html.twig
<h1>User</h1>

<table class="record_properties">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.id }}</td>
        </tr>
        <tr>
            <th>Username</th>
            <td>{{ entity.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ entity.email }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ entity.password }}</td>
        </tr>
        <tr>
            <th>Encrypted_password</th>
            <td>{{ entity.encryptedpassword }}</td>
        </tr>
        <tr>
            <th>Enabled</th>
            <td>{{ entity.enabled }}</td>
        </tr>
        <tr>
            <th>Accountexpired</th>
            <td>{{ entity.accountExpired }}</td>
        </tr>
        <tr>
            <th>Accountlocked</th>
            <td>{{ entity.accountLocked }}</td>
        </tr>
        <tr>
            <th>Roles</th>
            <td>{{ entity.stringRoles }}</td>
        </tr>
    </tbody>
</table>

<ul class="record_actions">
    <li>
        <a href="{{ path('user') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('user_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>
        <form action="{{ path('user_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>